[package]
name = "hamming_lsh"
version = "0.1.0"
authors = ["Jeremy Thorne <jez@jezandbecks.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.6.0", features = ["i128_support"] }
